name: Running Python

on:
  push:
    branches:
      - main

jobs:
  # first_lesson:
  #   name: Lesson 1 Printing
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.x'
  #   - name: run script
  #     run: python Lesson1Print.py
  #   - run: echo "üêç This job's status is ${{ job.status }}."
  # second_lesson:
  #   name: Lesson 2 Variables
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.x'
  #   - name: run script
  #     run: python Lesson2Variables.py
  #   - run: echo "üêç This job's status is ${{ job.status }}."
  third_lesson:
    name: Lesson 3 Number Operations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: run script
      run: python Lesson3NumOps.py
    - run: echo "üêç This job's status is ${{ job.status }}."